services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Test123
      MYSQL_DATABASE: travel_journal
      MYSQL_USER: db_user
      MYSQL_PASSWORD: user_password_here
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: